let arr = [ 1, 2, 3, 4, 5 ];
console.log(arr);
arr.push(6);
console.log(arr);
console.log(arr.length);
console.log(arr.indexOf(3));
console.log(arr.reverse());
console.log(arr);
console.log(arr.pop());
console.log(arr);